name: jembe_talk
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.11
  async: ^2.13.0
  
  # <<< DORE PAKI NSHYA TWONGEYEMO >>>
  cached_network_image: ^3.4.0 
  
  cached_video_player_plus: ^4.0.4
  video_player: ^2.8.6
  chewie: ^1.7.5

  cloud_firestore: ^6.0.0
  connectivity_plus: ^6.0.3
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  ffmpeg_kit_flutter_new: ^3.2.0
  file_picker: ^10.0.0
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.3
  firebase_storage: ^13.0.0
  flutter_cache_manager: ^3.3.1
  flutter_contacts: ^1.1.9+2
  flutter_emoji_selector_plus: ^0.0.9
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1

  # <<< DORE INDI PAKI NSHYA TWONGEYEMO >>>
  image: ^4.2.0
  
  image_editor_plus: any
  image_picker: ^1.1.2
  intl: ^0.20.0
  just_audio: ^0.9.37
  liquid_pull_to_refresh: ^3.0.1
  liquid_swipe: ^3.1.0
  media_store_plus: ^0.1.3
  package_info_plus: ^8.0.0
  page_flip_builder: 0.1.4
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  share_plus: ^11.0.0
  shared_preferences: ^2.2.3
  social_media_recorder: ^1.2.1
  sqflite: ^2.3.3+1
  url_launcher: ^6.2.1 
  youtube_player_flutter: ^9.0.0
  uuid: ^4.4.0
  video_editor: ^3.0.0
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  zego_uikit: ^2.28.24
  zego_uikit_prebuilt_call: ^4.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  record: ^5.0.5
  record_linux: ^1.0.0
  permission_handler: ^12.0.1
  zego_express_engine: ^3.11.0
  zego_zim: ^2.10.0
  just_audio: 0.10.4
  flutter_inappwebview: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: EmojiFont
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/jeme_talk_icon.png"
  min_sdk_android: 21